### ISSUE TITLE
Update to build projects for 2.13

### ISSUE THREAD

**Issue by wemrysi** [precog/sbt-precog#111]
In order for newer libraries that will use sbt-precog to build against more modern scala versions we want to remove support for older scala versions, instead focusing on building for 2.13 (and 3.0 eventually).

**Comment by wemrysi** [comment]
We'll probably want to do a major version bump on the plugin for this, we can always maintain a branch for the previous major version for the existing repos that aren't able to transition to the newer scala versions.

**Comment by rintcius** [comment]
Is it an idea to build for 2.13 only initially and later look into cross-building 3.0?

**Comment by wemrysi** [comment]
Yes, looks like 2.13 shouldn't be too bad, but we don't have to do 3.0 just now.

**Comment by alissapajer** [comment]
<1>

**Comment by alissapajer** [comment]
<0>
