### ISSUE TITLE
Add scalafmt to the build

### ISSUE THREAD

**Issue by wemrysi** [precog/sbt-precog#112]
We'd like to start using scalafmt everywhere, so adding it here seems reasonable. We can start with the rules from [precog/precog](https://github.com/precog/precog) and iterate from there.

The `ci` command should be updated to check formatting and fail the build if not adherent, similar to checking for headers.

**Comment by alissapajer** [comment]
Will this require adding `scalafmt` to all of our existing (v2) repos? Or could we opt-in just the new repos and repos we know we're using for v3? I want to avoid spending time reformatting existing repos, if this turns out to be hard for some reason we have yet to discover.

**Comment by wemrysi** [comment]
No, it shouldn't. I'd prefer if the main branch here can progress forward for new things (clear out stuff we don't need, add `scalafmt`, switch to 2.13, etc) and we branch if we need to backport something to the existing usages. I'm not sure if trickle is enabled for this, if so we probably want to go around and remove it from repos to avoid the bumps.

**Comment by rintcius** [comment]
Will also drop Java 8 support as part of this issue.

**Comment by rintcius** [comment]
<1>

**Comment by rintcius** [comment]
<0>
